<?php

namespace Esolving\ShopcartBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartModerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartModerationRepository extends EntityRepository {

    public function findAllByStatus($xstatus) {
        $q = $this->createQueryBuilder('cartModeration')
                ->addSelect('cartModeration_cart', 'cartModeration_cart_user')
                ->join('cartModeration.cart', 'cartModeration_cart')
                ->join('cartModeration_cart.user', 'cartModeration_cart_user')
                ->where('cartModeration.success = :cartModeration_success')
                ->setParameter(':cartModeration_success', $xstatus)
                ->getQuery()
        ;
        return $q->getResult();
    }

}
