<?php

namespace Esolving\ShopcartBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function findAllByLanguage($xlanguage) {
        $qb = $this->createQueryBuilder('category');
        $q = $qb->addSelect('languages')
                ->join('category.languages', 'languages')
                ->where($qb->expr()->eq('languages.language', ':language'))
                ->andWhere($qb->expr()->eq('category.status', ':status'))
                ->setParameter('language', $xlanguage)
                ->setParameter('status', '1')
                ->getQuery()
        ;
        return $q->getResult();
    }

}
