parameters:
#    esolving_shopcart_bundle_third_sonata_admin.example.class: Esolving\ShopcartBundle\Third\SonataAdminBundle\Example

services:
#    esolving_shopcart_bundle_third_sonata_admin.example:
#        class: %esolving_shopcart_bundle_third_sonata_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
